name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Discard all local git changes
        run: git checkout -- .
        continue-on-error: true

      - uses: actions/checkout@v2.4.0

      - name: Create docker swarm secret
        run: |
          echo "${{ secrets.DB_PASSWORD }}" | docker secret create db_password -
        continue-on-error: true

      - name: Deploy containers
        run: |
          docker stack deploy -c docker-compose.yml wiki